# Site settings
author: Tyler Carroll
title: 
header-img: img/home-bg.png
email: tylercarroll1611@gmail.com
copyright_name: Tyler Carroll
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Tyler320sc

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
